services:
  - type: web
    runtime: docker
    name: buildify
    rootDir: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: buildify-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

databases:
  - name: buildify-db
    plan: free
