# Generated by Django 5.2.10 on 2026-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_generatedfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="ai_model",
            field=models.CharField(
                choices=[
                    ("gemini-2.5-flash", "Gemini 2.5 Flash"),
                    ("gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite"),
                    ("gemini-2.5-pro", "Gemini 2.5 Pro"),
                    ("gemini-2.0-flash", "Gemini 2.0 Flash"),
                    ("gemini-3-flash", "Gemini 3 Flash"),
                    ("gemini-3.1-flash-lite", "Gemini 3.1 Flash Lite"),
                    ("gemini-3.5-flash", "Gemini 3.5 Flash"),
                    ("gemini-3.6-flash", "Gemini 3.6 Flash"),
                    ("gemini-3.7-flash", "Gemini 3.7 Flash"),
                    ("gemini-3.8-flash", "Gemini 3.8 Flash"),
                    ("gemma-4-26b-a4b-it", "Gemma 4 26B A4B IT"),
                    ("gemma-4-31b-it", "Gemma 4 31B IT"),
                    ("openai/gpt-oss-120b", "Groq - GPT OSS 120B"),
                    ("openai/gpt-oss-20b", "Groq - GPT OSS 20B (Fast)"),
                    ("deepseek/deepseek-chat-v3.1", "DeepSeek Chat V3.1"),
                    ("nex-agi/nex-n2.5-pro:free", "Nex AGI N2.5 Pro (Free)"),
                    ("google/gemini-2.5-flash", "Google Gemini 2.5 Flash"),
                    ("openai/gpt-4.1-mini", "OpenAI GPT-4.1 Mini"),
                    (
                        "meta-llama/llama-3.3-70b-instruct",
                        "Meta Llama 3.3 70B Instruct",
                    ),
                    (
                        "mistralai/mistral-small-3.1-24b-instruct",
                        "Mistral Small 3.1 24B Instruct",
                    ),
                    ("poolside/poolside-laguna-s-2.1", "Poolside Laguna S 2.1"),
                    ("poolside/poolside-laguna-xs-2.1", "Poolside Laguna XS 2.1"),
                    ("cohere/north-mini-code", "Cohere North Mini Code"),
                    ("dots3/dots3-note", "Dots3-Note"),
                    ("thinking-machines/inkling", "Thinking Machines Inkling"),
                ],
                default="nex-agi/nex-n2.5-pro:free",
                max_length=100,
            ),
        ),
    ]
