# Generated by Django 4.2.30 on 2026-10-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedfile',
            name='added_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedfile',
            name='line_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedfile',
            name='removed_lines',
            field=models.IntegerField(default=0),
        ),
    ]
